spring:
  application:
    name: zinsen-api
  profiles:
    active: production #production #local
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

