app:
  environment:
    description: Local
    test: true
    code: local

spring:
  datasource:
    url: jdbc:sqlserver://zinsen-db-srv.database.windows.net:1433;database=local-zinsen-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: server-admin
    password: FFHS@Project!
    hikari:
      maximum-pool-size: 10000
      connection-timeout: 300000 # 5 minutes
      validation-timeout: 300000 # 5 minutes
      max-lifetime: 300000 # 5 minutes
      idle-timeout: 300000 # 5 minutes

  jpa:
    show-sql: false

me:
  ruosch:
    calculate-url: http://localhost:7071/api/calculation

azure:
  application-insights:
    instrumentation-key: 37402c98-17e2-4f2c-a6ac-0355e698ff34
    web:
      enable-W3C: true
      enable-W3C-backcompat-mode: false



